### PR TITLE
Published package contains no code

### LINKED ISSUE #149: Published package contains no code
Within a client project, using `waterfall-cli` version 0.3.0, I am seeing:

```
internal/modules/cjs/loader.js:300
      throw err;
      ^

Error: Cannot find module '/Users/peterbelbin/gitlab/spark/node_modules/waterfall-cli/dist/index.js'. Please verify that the package.json has a valid "main" entry
.
.
.

code: 'MODULE_NOT_FOUND',
  path: '/Users/peterbelbin/gitlab/spark/node_modules/waterfall-cli/package.json',
  requestPath: 'waterfall-cli'
```

The waterfall-cli package.json file has a 'main' entry, which directs towards 'dist/index.js` (which does not exist).

I compared the contents of the 0.2.0 against 0.3.0.

0.2.0 has the 'main' property set to 'src/index.js', and has the 'src' folder within it (with JavaScript files).
0.3.0 has the 'main' property set to 'dist/index.js', but, has no 'dist' folder.

### PR DESCRIPTION
**Pull request by pbelbin**
Closes #149

### CODE REVIEW

**Comment by pbelbin** [comment]
I tested this with 'npm pack' and the resulting tarball looks good to me.

**Comment by WesCossick** [comment]
Can you point to documentation that supports these changes?

**Comment by pbelbin** [comment]
> Can you point to documentation that supports these changes?

About the need / use of .npmignore and how npm uses the .gitignore (if found) also:

[https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)

Regarding the `files` entry:
[https://docs.npmjs.com/files/package.json#files](https://docs.npmjs.com/files/package.json#files)

Regarding the `directories` entry: 
[https://docs.npmjs.com/files/package.json#directories](https://docs.npmjs.com/files/package.json#directories)

**Comment by pbelbin** [comment]
I'm a little bit suspicious that this may not be the entire solution.

`npm pack` (which generates a tarball) seems to work ok even without the .npmignore file.

So, I'm curious now about the travis process that's doing the release, and, whether the results of the `npm run compile` are being used when the packaging is done, or, whether this is happening in isolation, which would still result in the tarball not having the needed contents.

**Comment by WesCossick** [comment]
Based on the `directories` key documentation, it doesn’t appear to be very useful. Until it becomes useful, I think it’d be better to avoid using it altogether.

**Comment by pbelbin** [comment]
This may also be a factor:

skip_cleanup: true

[https://docs.travis-ci.com/user/deployment/npm/#releasing-build-artifacts](https://docs.travis-ci.com/user/deployment/npm/#releasing-build-artifacts)

**Comment by pbelbin** [comment]
I found elsewhere a [write-up](https://medium.com/@russleyshaw/typescript-package-deployment-with-travisci-df788ffb8563) that suggests that the 'skip_cleanup' may well be the main thing that is needed.

**Pull request merged**
